name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Run Unit Tests
        run: go test -json ./internal/database > test-results.json
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results.json
          path: test-results.json
