name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Run Unit Tests
        run: |
          go test -coverprofile coverage.out -json ./... > test-results.json
          go tool cover -func coverage.out
          go tool cover -html coverage.out -o test-coverage.html
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results.json
          path: test-results.json
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage.html
          path: test-coverage.html
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Check Code Formatting
        run: gofmt -l .
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62